[package]
name = "raytracing"
version = "0.1.0"
authors = ["tomon9086 <tomon9086@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
image = "0.24.2"
rgb = "0.8.33"
